# Generated by Django 5.2.15 on 2026-08-25 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ciu_portal', '0004_test_is_results_released_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='assigned_courses',
            field=models.ManyToManyField(blank=True, related_name='assigned_students', to='ciu_portal.course'),
        ),
        migrations.AddField(
            model_name='user',
            name='faculty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='ciu_portal.faculty'),
        ),
    ]
