# Generated by Django 5.2.15 on 2026-08-25 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ciu_portal', '0005_user_assigned_courses_user_faculty'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='reg_number',
            field=models.CharField(blank=True, help_text='Official Registration Number (e.g. 2026/CIU/BIT/001)', max_length=50, null=True),
        ),
    ]
