# Generated by Django 5.2.15 on 2026-08-26 05:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ciu_portal', '0006_user_reg_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='classtimetable',
            name='class_date',
            field=models.DateField(blank=True, help_text='Specific calendar date for the class slot', null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'role__in': ['dean', 'dvc', 'vc']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_applications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('lecturer', 'Lecturer'), ('dean', 'Faculty Dean'), ('faculty_admin', 'Faculty Secretary (Admin)'), ('registrar', 'Academic Registrar'), ('dvc', 'Chancellor (DVC)'), ('vc', 'Vice-Chancellor (VC)'), ('admin', 'System Admin')], max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('lecturer', 'Lecturer'), ('dean', 'Faculty Dean'), ('faculty_admin', 'Faculty Secretary (Admin)'), ('registrar', 'Academic Registrar'), ('dvc', 'Chancellor (DVC)'), ('vc', 'Vice-Chancellor (VC)'), ('admin', 'System Admin')], default='student', max_length=20),
        ),
    ]
