# Generated by Django 5.2.15 on 2026-09-10 08:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ciu_portal', '0007_classtimetable_class_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='is_active',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='test',
            name='is_published',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='reg_number',
            field=models.CharField(blank=True, db_index=True, help_text='Official Registration Number (e.g. 2026SOBAT-A001)', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('lecturer', 'Lecturer'), ('dean', 'Faculty Dean'), ('faculty_admin', 'Faculty Secretary (Admin)'), ('registrar', 'Academic Registrar'), ('dvc', 'Chancellor (DVC)'), ('vc', 'Vice-Chancellor (VC)'), ('admin', 'System Admin')], db_index=True, default='student', max_length=20),
        ),
        migrations.CreateModel(
            name='ProctorSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_data', models.TextField(help_text='Base64 data URL string for camera snapshot')),
                ('tab_switches_count', models.IntegerField(default=0)),
                ('is_camera_active', models.BooleanField(default=True)),
                ('flag_reason', models.CharField(blank=True, max_length=255, null=True)),
                ('captured_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('exam', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proctor_snapshots', to='ciu_portal.exam')),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='proctor_snapshots', to=settings.AUTH_USER_MODEL)),
                ('test', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proctor_snapshots', to='ciu_portal.test')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_banks', to='ciu_portal.course')),
                ('course_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='question_banks', to='ciu_portal.courseunit')),
                ('created_by', models.ForeignKey(limit_choices_to={'role': 'lecturer'}, on_delete=django.db.models.deletion.CASCADE, related_name='question_banks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionBankItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('question_type', models.CharField(choices=[('mcq', 'Multiple Choice'), ('tf', 'True / False'), ('short', 'Short Answer')], default='mcq', max_length=10)),
                ('option_a', models.CharField(blank=True, max_length=255, null=True)),
                ('option_b', models.CharField(blank=True, max_length=255, null=True)),
                ('option_c', models.CharField(blank=True, max_length=255, null=True)),
                ('option_d', models.CharField(blank=True, max_length=255, null=True)),
                ('correct_answer', models.CharField(max_length=255)),
                ('points', models.FloatField(default=1.0)),
                ('explanation', models.TextField(blank=True, null=True)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='ciu_portal.questionbank')),
            ],
        ),
        migrations.CreateModel(
            name='TemporaryClearance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clearance_type', models.CharField(choices=[('both', 'Tests & Exams (50% & 100% Gates)'), ('tests', 'Tests Only (50% Gate)'), ('exams', 'Exams Only (100% Gate)')], default='both', max_length=20)),
                ('valid_from', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('reason', models.TextField(blank=True, default='Financial Guarantee / Dean Approval')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_clearances', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='temporary_clearances', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
