# Generated by Django 5.2.15 on 2026-09-10 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ciu_portal', '0008_alter_exam_is_active_alter_test_is_published_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='must_change_password',
            field=models.BooleanField(default=False, help_text='Flag indicating student must change one-time password on login'),
        ),
    ]
