# Generated by Django 5.2.15 on 2026-09-10 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ciu_portal', '0009_user_must_change_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='classtimetable',
            name='year_of_study',
            field=models.IntegerField(choices=[(0, 'All Years'), (1, 'Year 1'), (2, 'Year 2'), (3, 'Year 3'), (4, 'Year 4')], default=0, help_text='Target academic year of study'),
        ),
        migrations.AddField(
            model_name='exam',
            name='year_of_study',
            field=models.IntegerField(choices=[(0, 'All Years'), (1, 'Year 1'), (2, 'Year 2'), (3, 'Year 3'), (4, 'Year 4')], default=0, help_text='Target academic year of study (0 for All Years, 1-4 for specific year)'),
        ),
        migrations.AddField(
            model_name='examtimetable',
            name='year_of_study',
            field=models.IntegerField(choices=[(0, 'All Years'), (1, 'Year 1'), (2, 'Year 2'), (3, 'Year 3'), (4, 'Year 4')], default=0, help_text='Target academic year of study'),
        ),
        migrations.AddField(
            model_name='test',
            name='year_of_study',
            field=models.IntegerField(choices=[(0, 'All Years'), (1, 'Year 1'), (2, 'Year 2'), (3, 'Year 3'), (4, 'Year 4')], default=0, help_text='Target academic year of study'),
        ),
        migrations.AddField(
            model_name='user',
            name='year_of_study',
            field=models.IntegerField(choices=[(1, 'Year 1'), (2, 'Year 2'), (3, 'Year 3'), (4, 'Year 4')], default=1, help_text='Academic Year of Study for students (1-4)'),
        ),
        migrations.AlterField(
            model_name='user',
            name='tuition_paid_percentage',
            field=models.FloatField(default=0.0, help_text='Tuition clearance percentage (0.0 to 100.0)'),
        ),
    ]
