# Generated by Django 5.2.15 on 2026-09-10 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ciu_portal', '0010_classtimetable_year_of_study_exam_year_of_study_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='duration_years',
            field=models.IntegerField(choices=[(1, '1 Year'), (2, '2 Years'), (3, '3 Years'), (4, '4 Years'), (5, '5 Years')], default=3, help_text='Duration of the course in academic years'),
        ),
        migrations.AddField(
            model_name='courseunit',
            name='year_of_study',
            field=models.IntegerField(choices=[(1, 'Year 1'), (2, 'Year 2'), (3, 'Year 3'), (4, 'Year 4')], default=1, help_text='Academic Year of Study for this course unit (1-4)'),
        ),
    ]
