# Generated by Django 5.2.15 on 2026-09-11 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ciu_portal', '0011_course_duration_years_courseunit_year_of_study'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
