# Generated by Django 5.2.15 on 2026-09-15 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ciu_portal', '0012_exam_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('lecturer', 'Lecturer'), ('dean', 'Faculty Dean'), ('faculty_admin', 'Faculty Secretary (Admin)'), ('registrar', 'Academic Registrar'), ('dvc', 'Chancellor (DVC)'), ('vc', 'Vice-Chancellor (VC)'), ('platform_coordinator', 'Platform Coordinator'), ('admin', 'System Admin')], max_length=35),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('lecturer', 'Lecturer'), ('dean', 'Faculty Dean'), ('faculty_admin', 'Faculty Secretary (Admin)'), ('registrar', 'Academic Registrar'), ('dvc', 'Chancellor (DVC)'), ('vc', 'Vice-Chancellor (VC)'), ('platform_coordinator', 'Platform Coordinator'), ('admin', 'System Admin')], db_index=True, default='student', max_length=35),
        ),
    ]
